name: Test and coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      # - run: npm run build --if-present
      - run: npm test

      - name: Test coverage (Codecov.com)
        uses: codecov/codecov-action@v2
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./__test__/reports/clover.xml # optional
          # flags: unittests # optional
          # name: codecov-umbrella # optional
          # fail_ci_if_error: false # optional (default = false)
          # verbose: true # optional (default = false)
      
      - name: Publish code coverage to Codeclimate.com
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 15ecb7c2e52ea0fef2aa73c09d14ca3d6a875195a33538da0046bd5844fb467d
        with:
          coverageLocations: |
            ${{github.workspace}}/__test__/reports/lcov.info:lcov  
      
      - name: Update README
        run: |-
          npm run badges
          cat README.md
      - name: Commit and push
        run: |-
          git add README.md
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push
